### ISSUE TITLE
您好，程序运行中途闪退，下面是视频信息

### ISSUE THREAD

**Issue by Jocbin** [Thomasyse/BDMatch#1]
=====TV VIDEO :
Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : isom (isom/iso2/avc1/mp41)
File size                   : 6.22 GiB
Duration                    : 2 h 36 min
Overall bit rate mode       : Variable
Overall bit rate            : 5 699 kb/s
Writing application         : Bandicut 3.1.5.509 / Cutter / HS+

Video
ID                          : 1
Format                      : AVC / AVC
Format/Info                 : Advanced Video Codec
Format profile              : Main@L4 / Main@L4
Format settings             : CABAC / 1 Ref Frames / CABAC / 1 Ref Frames
Format settings, CABAC      : Yes / Yes
Format settings, Reference  : 1 frame / 1 frame
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 2 h 36 min
Bit rate mode               : Variable
Bit rate                    : 5 563 kb/s
Maximum bit rate            : 16.0 Mb/s
Width                       : 1 920 pixels
Original width              : 1 920 pixels / 1 920 pixels
Height                      : 1 080 pixels
Original height             : 1 080 pixels / 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Variable
Frame rate                  : 29.970 (29970/1000) FPS
Minimum frame rate          : 13.716 FPS
Maximum frame rate          : 29.970 FPS
Original frame rate         : 29.970 (30000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0 / 4:2:0
Bit depth                   : 8 bits / 8 bits
Scan type                   : Progressive / Progressive
Bits/(Pixel*Frame)          : 0.090
Stream size                 : 6.07 GiB (98%)
Codec configuration box     : avcC

Audio
ID                          : 2
Format                      : AAC LC
Format/Info                 : Advanced Audio Codec Low Complexity
Codec ID                    : mp4a-40-2
Duration                    : 2 h 36 min
Bit rate mode               : Constant
Bit rate                    : 128 kb/s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 44.1 kHz
Frame rate                  : 43.066 FPS (1024 SPF)
Compression mode            : Lossy
Stream size                 : 143 MiB (2%)
Default                     : Yes
Alternate group             : 1

=====================================================
=====BD VIDEO :
Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : isom (isom/iso2/avc1/mp41)
File size                   : 6.55 GiB
Duration                    : 2 h 36 min
Overall bit rate mode       : Variable
Overall bit rate            : 5 986 kb/s
Writing application         : Lavf57.72.101

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : Main@L4
Format settings             : CABAC / 3 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 3 frames
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 2 h 36 min
Bit rate mode               : Variable
Bit rate                    : 5 744 kb/s
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Variable
Frame rate                  : 29.970 (29970/1000) FPS
Minimum frame rate          : 29.960 FPS
Maximum frame rate          : 30.060 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.092
Stream size                 : 6.26 GiB (96%)
Writing library             : x264 core 148 r2665 a01e339
Encoding settings           : cabac=1 / ref=3 / deblock=1:1:1 / analyse=0x1:0x111 / me=hex / subme=6 / psy=1 / psy_rd=0.50:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=18 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=0 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=2 / b_pyramid=0 / b_adapt=1 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=1 / keyint=250 / keyint_min=25 / scenecut=0 / intra_refresh=0 / rc_lookahead=10 / rc=cbr / mbtree=1 / bitrate=5744 / ratetol=1.0 / qcomp=0.60 / qpmin=5 / qpmax=69 / qpstep=4 / vbv_maxrate=5744 / vbv_bufsize=12000 / nal_hrd=vbr / filler=0 / ip_ratio=1.40 / aq=1:1.00
Codec configuration box     : avcC

Audio
ID                          : 2
Format                      : AAC LC
Format/Info                 : Advanced Audio Codec Low Complexity
Codec ID                    : mp4a-40-2
Duration                    : 2 h 36 min
Bit rate mode               : Constant
Bit rate                    : 256 kb/s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 44.1 kHz
Frame rate                  : 43.066 FPS (1024 SPF)
Compression mode            : Lossy
Stream size                 : 287 MiB (4%)
Default                     : Yes
Alternate group             : 1

**Comment by Thomasyse** [comment]
是在什么位置闪退呢，程序有没有输出什么信息？
如果可以的话能不能提供一下运行环境？

**Comment by Jocbin** [comment]
操作系统	Windows 10 Enterprise 64位 ( DirectX 12 ) x64 Windows 10 Version 1909 (KB4534132)
处理器	英特尔 Core i7-7700K @ 4.20GHz 四核
主板	华硕 PRIME Z270M-PLUS ( Z270 芯片组 )
内存	16 GB ( 芝奇 DDR4 2400MHz )
主硬盘	三星 MZVLW256HEHP-00000 ( 256 GB / 固态硬盘 )
显卡	Nvidia GeForce GTX 1070 Ti ( 8 GB / 技嘉 )

运行库
Microsoft Visual C+ + 2005 Redistributable
Microsoft Visual C+ + 2005 Redistributable 
Microsoft Visual C+ + 2008 Redistributable 
Microsoft Visual C+ + 2008 Redistributable 
Microsoft Visual C+ + 2008 Redistributable 
Microsoft Visual C+ + 2008 Redistributable 
Microsoft Visual C++ 2010 x64 Redistributable
Microsoft Visual C+ + 2010 x86 Redistributable...
Microsoft Visual C+ + 2012 Redistributable 
Microsoft Visual C+ + 2012 Redistributable 
Microsoft Visual C+ + 2013 Redistributable (x...
Microsoft Visual C+ + 2013 Redistributable (x...
Microsoft Visual C+ + 2013 Redistributable (x...
Microsoft Visual C+ + 2013 Redistributable (x...
Microsoft Visual C+ + 2013 Redistributable (x..
Microsoft Visual C+ + 2015- 2019 Redistributab...
Microsoft Visual C+ + 2015- 2019 Redistributab...
您好，以上就是我的系统信息。
之前我使用您开发的这个软件调整别的视频时间轴没有问题，但是打开上面两个视频运行到进度条大概在40%到50%之间时，就卡住了两三秒，然后程序窗口消失直接闪退了，看不到程序输出的信息。如果您需要的话，我可以把我能顺利运行的视频信息和不能顺利运行的信息发给您，供您查看。

**Comment by Thomasyse** [comment]
嗯……如果可以的话能不能把有问题的音轨和字幕发给我呢？我看看能不能复现。

**Comment by Jocbin** [comment]
[视频和ASS字幕.zip](https://github.com/Thomasyse/BDMatch/files/4143469/ASS.zip)

**Comment by Jocbin** [comment]
您好，不是我无中生有，这个真是我朋友测试的视频

**Comment by Thomasyse** [comment]
收到了，不过我下载需要蛮长的时间，你可能得等一两天……

**Comment by Jocbin** [comment]
我正在上传到奶牛快传可以让您不限速下载。我也可以上传到百度，但是只有会员才可以不限速下载。

**Comment by Jocbin** [comment]
您好，我已经上传到奶牛快传，可以不限速下载，在奶牛快传首页（cowtransfer.com）输入取件码：vgmhri (24小时内有效) 查看文件列表，或直接点击取件链接：https://c-t.work/s/1a0e5c58fb7e45 查看文件列表。感谢大佬开发的这款软件，我用起来非常好用，大部分视频匹配时间轴非常好用，唯独上面这两个视频出现问题。但是您的软件已经解决我99%的问题了，对此非常感谢。

**Comment by Jocbin** [comment]
忘了，还有有一个文件提取密码：bdmatch

**Comment by Thomasyse** [comment]
收到，我等下载完看看。

**Comment by Jocbin** [comment]
麻烦您了

**Comment by Thomasyse** [comment]
问题已经解决，过一会发布，你试了没有其它问题的话我就关闭这个问题了。

**Comment by Jocbin** [comment]
好的  谢谢大佬

**Comment by Jocbin** [comment]
好的，大佬。我已经试完了，没有问题。但是关于设置的小问题想问一下，出现前一行或后一行次序不一致这种情况，是不是只能按照增加精度并且降低效率来减少这种情况，并不能完全避免，还是需要人工检查警告的时间轴？

**Comment by Thomasyse** [comment]
如果是你刚才那两个视频的话，把搜索范围改大一点就行了，我用30秒试就没有问题。如果有警告一般还是建议人工确认一下是什么问题。通常都是通过调整搜索范围和增加确认次数来解决，确认次数可以调得很大，在搜索范围较小的情况下对性能影响不会特别明显。

**Comment by Thomasyse** [comment]
还有一种情况就是如果两个音频音量差距很大的话需要打开响度匹配，要不然也会有匹配错误出现。

**Comment by Jocbin** [comment]
我已经按照您的方式试过，效果很好，设置我听了您的解释明白了。软件设置也很简单，设置旁边就有详细的说明，可见大佬用心良苦。我会把这个软件介绍给论坛里和我一样的朋友，虽然和您做这个软件的初衷不一样，但是您这个软件其实可以用来给提取以前硬字幕视频的字幕来匹配新出的高清资源非常非常非常有帮助。

**Comment by Jocbin** [comment]
而不光是给日本动漫tv版和bd版字幕调校转换

**Comment by Thomasyse** [comment]
不客气，那我把问题关了。
