### ISSUE TITLE
新版本匹配率远低于旧版本软件

### ISSUE THREAD

**Issue by linlihong1984** [Thomasyse/BDMatch#10]
您好，我在使用中发现同样的参数设定，使用旧版本1.5.20可以完美匹配，但是使用最新的2.0.1版本却出现大量错误，具体截图如下：

使用1.5.20匹配时，有三个提醒，属于完美匹配

![1111](https://github.com/Thomasyse/BDMatch/assets/49052929/7c8c913c-aa2f-4344-b52a-fba94dcda58d)

生成的SRT文件，时间轴正确

![Snipaste_2024-05-30_19-02-01](https://github.com/Thomasyse/BDMatch/assets/49052929/ed4080ed-77fe-49d0-8194-2182ff7abcc9)

使用2.0.1匹配时，警告28个，信息3个，另有一个提示超过音频长度

![Snipaste_2024-05-30_19-04-37](https://github.com/Thomasyse/BDMatch/assets/49052929/8e33b158-8465-490d-963a-4870ddca54a1)
![Snipaste_2024-05-30_19-04-48](https://github.com/Thomasyse/BDMatch/assets/49052929/8b8f18ce-61ac-411e-8c46-7e18fd9fc1dc)

生成的SRT文件，时间轴大量错误

![Snipaste_2024-05-30_19-05-45](https://github.com/Thomasyse/BDMatch/assets/49052929/e3f6c999-dd43-4fc8-93bc-662aaeeb44a7)

以上用的是同样的文件，同样的参数设置，但是效果却相差很大，是我哪里用得不对吗

使用您的软件很长时间了，可以给您提两点小建议吗？

1.关于“响度补偿”这个选项，不知道能不能做成自动识别视频响度是否需要补偿，或者在“响度补偿”选项未选中时，在视频提取完成后，能不能显示两个视频的响度以便我判断是否需要补偿响度，比如我在使用中选中“响度补偿”，在视频提取完成后，软件会提示响度补偿详情，这样我可以判断补偿后是否更接近TV视频响度，从而选择让软件继续工作还是停止转而取消补偿。

2.能不能加一个命令行启动的功能，这样我能更方便从CMD中启动它，启动后从命令行自动获取并填写BD,TV,SUB等路径

以上如果对您造成困扰，请见谅

**Comment by Thomasyse** [comment]
如果可以的话能把文件发给我看一下吗？发视频太大的话可以只发音频。如果不能发文件的话也至少把设置参数发一下。
响度补偿的话可以加一个选项让在多少响度差距以上才补偿，但是对运行时间应该不会有帮助。理论上来说，如果你确定音量差距不大就不用开，如果不确定就打开，补偿后不应该会出现响度差距更大的情况。
如果要用命令行的话可以参考readme自己编译一个，但是得自己设置语言为英语，要不然输出会有乱码。
