### ISSUE TITLE
部分视频匹配提示"错误：无法打开文件！“

### ISSUE THREAD

**Issue by joy-W771** [Thomasyse/BDMatch#11]
使用提取音频匹配也一样的提示
小部分视频音频压制同意码率后可以匹配
![PixPin_2024-06-21_02-26-09](https://github.com/Thomasyse/BDMatch/assets/72702761/41d2e49a-93fe-4520-b930-e75e311113ba)

**Comment by Thomasyse** [comment]
这个是FFmpeg报的错。你可以用新的2.0.3版本试试，可以看到FFmpeg的错误信息。
