### ISSUE TITLE
关于生成的srt字幕符号错误

### ISSUE THREAD

**Issue by Jocbin** [Thomasyse/BDMatch#3]
**Describe the bug**
目前软件经过作者大佬更新，感觉非常好用，对此表示感谢。但是还有两个小问题向您反馈：
        第一个问题稍微重要点，就是目前BDMatch生成的srt字幕时间轴的秒与毫秒之间用英文句号“.”表示，如下图所示：
![image](https://user-images.githubusercontent.com/60310930/79680345-4f1ce400-8241-11ea-88c9-1d9137d99af2.png)
       在常用的字幕编辑软件如aegisub和subtitleedit等，会出错或者报错，如下图所示：
![image](https://user-images.githubusercontent.com/60310930/79680374-7e335580-8241-11ea-8518-aecaec385b03.png)
![image](https://user-images.githubusercontent.com/60310930/79680382-973c0680-8241-11ea-829f-d7c16b082a32.png)
       根据维基百科中关于SRT字幕的说明， SubRip (SubRip Text) files are named with the extension .srt, and contain formatted lines of plain text in groups separated by a blank line. Subtitles are numbered sequentially, starting at 1. The timecode format used is hours:minutes:seconds,milliseconds with time units fixed to two zero-padded digits and fractions fixed to three zero-padded digits (00:00:00,000). The fractional separator used is the comma, since the program was written in France.
       因此srt字幕正确的格式是将秒与毫秒之间用英文逗号","表示，如下图所示
![image](https://user-images.githubusercontent.com/60310930/79680400-ceaab300-8241-11ea-9893-c237a3eaa171.png)

第二个无关紧要，就是字幕打开的界面，既然已经支持ASS和SRT两种字幕格式，可不可以将ALL FILES代替ASS FILES成为默认选项，避免有人误以为不支持srt格式。
![image](https://user-images.githubusercontent.com/60310930/79680430-19c4c600-8242-11ea-8ebd-5b283d6f60af.png)

**To Reproduce**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
 - CPU: [e.g. Intel Core i7 6700K]
 - BDMatch Version: [e.g. 1.5.11]
 - Runtime: 
    [e.g. 
    .NET Framework 4.8
    Microsoft Visual C++ Redistributable for Visual Studio 2019
    etc.]

**Ouput of BDMatch**
Add text or screenshots here.

**Input files**
If applicable, upload the file itself is rather than the information.
 - Sub:
 - TV:
 - BD:

**Additional context**

**Comment by Thomasyse** [comment]
收到了，过会更新
没问题的话我过段时间就关了

**Comment by Jocbin** [comment]
非常感谢大佬，没问题了。
