### ISSUE TITLE
[Bug] BD视频文件路径有中文名，匹配后的ass文件中视频路径就会有编码错误

### ISSUE THREAD

**Issue by ghost** [Thomasyse/BDMatch#5]
**描述错误**
BD视频文件路径有中文名，匹配后的ass文件中视频路径就会有编码错误

**重现**
重现行为的步骤：
1. BD视频文件路径有中文名
`D:\新建文件夹\[ReinForce] Heya Camp△ (BDRip 1920x1080 x264 FLAC)\[ReinForce] Heya Camp△ 01 (BDRip 1920x1080 x264 FLAC).mkv`
2.匹配
3.生成文件如图，Aegisub生成的文件默认的编码好像是UTF-8 BOM
![image.png](https://i.loli.net/2020/05/30/vmqjed6H2ADLhO3.png)
用Aegisub打开报错
![image.png](https://i.loli.net/2020/05/30/dXw5ns93mzA7Pyj.png)
将编码改为ANSI后路径名正常
![image.png](https://i.loli.net/2020/05/30/e4Ehpx1cL6GYWaq.png)

**环境（请填写以下信息）：**
 - 操作系统：Windows 10 1909
 - CPU：Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - BDMatch版本：1.5.19
 - 运行时：
Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz：使用AVX、AVX2、FMA指令集加速。

**Comment by Thomasyse** [comment]
[BDMatch.zip](https://github.com/Thomasyse/BDMatch/files/4705285/BDMatch.zip)
试试这个

**Comment by ghost** [comment]
> [BDMatch.zip](https://github.com/Thomasyse/BDMatch/files/4705285/BDMatch.zip)
> 试试这个

用这个就没问题了
