### ISSUE TITLE
Could work with a single video?

### ISSUE THREAD

**Issue by Ruke805** [Thomasyse/BDMatch#6]
I made a test here with a video that has the right subtitle (DVD rip) to fix for a BD version and work very well, but in some cases, a second video is not available, in many cases we have a single version and a subtitle unsynced which needs to be synchronized, and the program does not accept only one file. Is there a way to just sync this subtitle with a single version of the video?

**Comment by Thomasyse** [comment]
This problem will be closed since it is the same as #7.
