### ISSUE TITLE
[Bug] 无法提交音频至解码器！

### ISSUE THREAD

**Issue by linlihong1984** [Thomasyse/BDMatch#8]
AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  ：使用AVX、AVX2、FMA指令集加速。
----------------------------------------------------------------------------------------------
BD文件：  jbd-285.mp4

无法提交音频至解码器！

其他视频字幕都是正常的，就这个跳出这个提示，请问是什么原因呢

**Comment by Thomasyse** [comment]
这个是ffmpeg的解码错误，你可以看看你的音频格式是否被ffmpeg支持。
