### ISSUE TITLE
2.0最新版本无法运行

### ISSUE THREAD

**Issue by linlihong1984** [Thomasyse/BDMatch#9]
我下载了您的最新版本，运行后提示需要安装WINDOWS APP SDK，我在弹出来的网站上下载了最新的1.5版本，安装的时候CMD窗口一闪而过，我试了很多种方法，但是无法安装上这个SDK，运行不了软件

真的很喜欢您的这个软件，帮了我很大的忙，看着有新版本却无法使用，心里抓狂

希望作者可以出一个包含SDK的版本

**Comment by Thomasyse** [comment]
试试2.0.1
